services:
  app_proxy:
    environment:
      APP_HOST: dy-xmr-mempool_frontend_1
      APP_PORT: 3002

  backend:
    image: ghcr.io/dy0x/xmr-mempool:backend-latest
    environment:
      PORT: 3001
      MONERO_NODE_1_HOST: ${APP_MONERO_NODE_IP}
      MONERO_NODE_1_PORT: ${APP_MONERO_RPC_PORT:-18081}
      MONERO_NODE_1_USER: ${APP_MONERO_RPC_USER}
      MONERO_NODE_1_PASS: ${APP_MONERO_RPC_PASS}
    restart: unless-stopped

  frontend:
    image: ghcr.io/dy0x/xmr-mempool:frontend-latest
    depends_on:
      - backend
    restart: unless-stopped
